import Link from 'next/link';
import UpcomingEvents from '@/components/UpcomingEvents';
import { PageHead } from '@/components/ui';
import { findRepoRoot } from '@/lib/repo-root';
import { buildReport, reviewPeriod, samePeriod, records } from '../../../../../../scripts/lib/business-direction.mjs';
import RecordPanel from './RecordPanel';
export const dynamic = 'force-dynamic';
const show = (value: number | null) => value == null ? '未計測' : value.toLocaleString('ja-JP');
export default async function BusinessPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const search = await searchParams, cadence = search.cadence === 'monthly' ? 'monthly' : 'weekly';
  const period = search.start && search.end ? { startDate: search.start, endDate: search.end } : reviewPeriod(cadence);
  let data: any;
  try { data = buildReport(findRepoRoot(), period); } catch { return <><PageHead title="事業方針と改善" /><p className="card">設定・計測期間を読み取れません。<Link href="/metrics/business">直近の週次へ戻る</Link></p></>; }
  const { strategy, cells } = data, scopes = [{ id: 'all', label: '全体' }, ...strategy.qualifications];
  const existingReview = data.reviews.find((r: any) => r.cadence === cadence && samePeriod(r.period, period));
  const previous = records(findRepoRoot()).filter((r: any) => r.kind === 'snapshot' && r.period.endDate < period.startDate && Math.round((Date.parse(r.period.endDate) - Date.parse(r.period.startDate)) / 86400000) === Math.round((Date.parse(period.endDate) - Date.parse(period.startDate)) / 86400000)).at(-1);
  return <>
    <PageHead title="事業方針と改善" sub="資格別の学習価値・販売・運営負担を同じ基準で振り返る" />
      <UpcomingEvents domain="strategy" />
    <div className="card business-direction"><p className="small">私たちが届ける価値</p><h2>{strategy.positioning}</h2><p>{strategy.objective}</p><div className="business-journey">受験者の課題 <span>→</span> 図で理解 <span>→</span> 過去問・答案で確認 <span>→</span> 必要な教材・支援</div><p className="small">図の枚数や検索順位だけで成果を判定しません。正確さ、学習行動、収益、運営時間を合わせて見ます。</p></div>
    <div className="business-grid">{strategy.qualifications.map((q: any) => <section className="card" key={q.id}><h2>{q.label}</h2><p className="small">{q.audience}</p><p>{q.promise}</p><ol>{q.journey.map((x: string) => <li key={x}>{x}</li>)}</ol><p className="small">有料の支援: {q.offer}</p></section>)}</div>
    <div className="card"><h2>確認する期間</h2><nav className="filterbar"><Link href="/metrics/business">前週</Link><Link href="/metrics/business?cadence=monthly">前月</Link><Link href="/metrics/seo-watch">検索順位の改善</Link><Link href="/sales">売上明細</Link><Link href="/todo">実装タスク</Link><Link href="/materials">教材からの展開</Link></nav><form className="filterbar"><input type="hidden" name="cadence" value={cadence} /><label>開始 <input aria-label="開始日" type="date" name="start" defaultValue={period.startDate} required /></label><label>終了 <input aria-label="終了日" type="date" name="end" defaultValue={period.endDate} required /></label><button>表示</button></form><p>{period.startDate}〜{period.endDate} · {cadence === 'monthly' ? '月次' : '週次'}<br /><span className="small">GSCは太平洋時間、運用記録は日本時間。各データの対象期間を揃えて表示し、期間が異なる計測を埋め合わせません。</span></p></div>
    <div className="card"><h2>資格別KPI</h2><p className="small">—は未計測、部分は登録・確認できた範囲、対象外は現在その資格で運用していない指標です。全体には重点資格外と未帰属を含みます。人数は資格間で足しません。資格別のGoogle計測は正規URL配下の範囲です。旧URLで閲覧されていた期間と直接比較して増減を効果としません。目標は基準値を確認後に設定します。</p><div className="table-wrap"><table className="data"><thead><tr><th>段階・指標</th>{scopes.map((q: any) => <th key={q.id}>{q.label}</th>)}</tr></thead><tbody>{strategy.metrics.map((m: any) => <tr key={m.id}><td><details><summary>{m.stage} · {m.label}</summary><p className="small">{m.definition}</p></details></td>{scopes.map((q: any) => { const cell = cells.find((x: any) => x.metric === m.id && x.qualification === q.id), prev = previous?.cells.find((x: any) => x.metric === m.id && x.qualification === q.id); return <td key={q.id}><strong>{cell.applicable === false ? '対象外' : show(cell.value)}{cell.value != null ? m.unit : ''}</strong>{cell.coverage === 'partial' && <span className="badge warn">部分</span>}{cell.target && <div className="small">目標 {cell.target.direction === 'at-most' ? '≤' : '≥'}{cell.target.value}{m.unit}</div>}{cell.value != null && prev?.value != null && <div className="small">以前の保存値 {show(prev.value)}（{previous.period.startDate}〜{previous.period.endDate}）</div>}<details className="small"><summary>範囲・出典</summary><p>{cell.note}</p><p className="mono">{cell.source ?? (cell.applicable === false ? '対象外' : '取得待ち')}</p></details></td>; })}</tr>)}</tbody></table></div></div>
    <div className="card"><h2>運営収支</h2><p className="small">同じ資格・期間の実受取と費用が両方確認できた場合だけ差額を表示します。未記録の費用や労働対価を含む利益の確定値ではありません。</p>{data.operatingBalance.map((b: any) => <p key={b.qualification}>{scopes.find((q: any) => q.id === b.qualification)?.label}: {b.value == null ? '受取・費用の確認待ち' : `${show(b.value)}円`}</p>)}</div>
    <div className="card"><h2>別期間の既存計測</h2><p className="small">上の対象期間には転記しません。最新の取得範囲を確認できます。</p>{data.sources.filter((r: any) => !samePeriod(r.period, period)).map((r: any, i: number) => <p key={i}>{strategy.metrics.find((m: any) => m.id === r.metric)?.label}: {show(r.value)} · {r.period.startDate}〜{r.period.endDate}<br /><span className="small mono">{r.source}</span></p>)}</div>
    <div className="card"><h2>レビューと次の改善</h2>{data.due.map((d: any) => <p key={d.cadence}><span className={`badge ${d.due ? 'warn' : 'good'}`}>{d.cadence === 'monthly' ? '月次' : '週次'} {d.due ? '要確認' : '記録あり'}</span> {d.period.startDate}〜{d.period.endDate} {d.status === 'provisional' ? '（欠測を含む暫定判断）' : ''}</p>)}{data.followups.map((r: any) => <p key={r.file}><Link href={`/metrics/business?cadence=${r.cadence}&start=${r.period.startDate}&end=${r.period.endDate}`}>暫定判断の再確認: {r.period.startDate}〜{r.period.endDate}</Link></p>)}{data.targetsDue.map((t: any) => <p key={t.file}>目標の見直し: {t.qualification} / {t.metric}（{t.reviewDate}）</p>)}<p>週次は実験の結果と次の一手。月次は資格・商品への配分と目標を見直します。観察中のSEO施策は7日間再編集せず、実験を増やす前に期限到来分を確認します。</p>{data.experiments.map((e: any) => <p key={e.id}>{e.id} · {e.title}<br /><span className={`badge ${e.overdue ? 'warn' : 'neutral'}`}>次回 {e.nextReviewDate ?? '未設定'}</span></p>)}</div>
    <RecordPanel strategy={strategy} period={period} cadence={cadence} existingReview={existingReview} observations={data.observations} />
    <div className="card"><h2>判断の履歴</h2>{data.reviews.length === 0 ? <p>レビューはまだ記録されていません。</p> : data.reviews.map((r: any) => <details key={r.file}><summary>{r.period.startDate}〜{r.period.endDate} · {r.cadence === 'monthly' ? '月次' : '週次'} · 次回 {r.nextReviewDate}</summary><p>{r.findings}</p><p><strong>判断:</strong> {r.decision}</p><p><strong>次:</strong> {r.nextAction}</p></details>)}</div>
    <div className="card"><h2>個別の商品・計測記録</h2>{data.observations.filter((r: any) => samePeriod(r.period, period)).map((r: any) => <details key={r.file}><summary>{r.channel} · {r.qualification} · {r.subject}</summary><p>{Object.entries(r.values).map(([k,v]) => `${strategy.metrics.find((m: any) => m.id === k)?.label}: ${v ?? '未計測'}`).join(' / ')}</p><p className="small">{r.source}</p></details>)}</div>
    <div className="card"><h2>共通の運用ルール</h2><ul>{strategy.rules.map((r: string) => <li key={r}>{r}</li>)}</ul><p className="small">集客の継続指標: {strategy.northStar.role}<br />学習価値を表す次の指標: {strategy.northStar.candidate}。{strategy.northStar.readiness}</p><p className="mono small">npm run fetch-business-metrics -- --commit<br />npm run business-review -- report<br />npm run business-review -- report --monthly<br />npm run check-business-direction</p></div>
  </>;
}
