/**
 * scripts/sync-codex-compat.mjs（DN-0098）のテスト。
 *
 * 実スクリプトはリポジトリルートを import.meta.url から解決するため、各テストは
 * 一時ディレクトリに「scripts/sync-codex-compat.mjs」を自分自身のコピーとして配置し、
 * そこを subprocess で起動する（本物の AGENTS.md / .agents / Git index には一切触れない）。
 */
import { strict as assert } from 'node:assert';
import test from 'node:test';
import { mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { mkdtempSync } from 'node:fs';
import { spawnSync, execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const REAL_SCRIPT = join(dirname(fileURLToPath(import.meta.url)), '..', 'scripts', 'sync-codex-compat.mjs');
const REAL_SCRIPT_SRC = readFileSync(REAL_SCRIPT, 'utf8');

const fixtures = [];
test.after(() => {
  for (const f of fixtures) rmSync(f, { recursive: true, force: true });
});

function writeFile(root, relPath, content) {
  const abs = join(root, relPath);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
}

function makeFixture({ git = false } = {}) {
  const root = mkdtempSync(join(tmpdir(), 'sync-codex-compat-'));
  fixtures.push(root);
  writeFile(root, 'scripts/sync-codex-compat.mjs', REAL_SCRIPT_SRC);
  if (git) execFileSync('git', ['init', '-q'], { cwd: root });
  return root;
}

function run(root, args) {
  const res = spawnSync(process.execPath, [join(root, 'scripts/sync-codex-compat.mjs'), ...args], {
    cwd: root,
    encoding: 'utf8',
  });
  return { status: res.status, stdout: res.stdout ?? '', stderr: res.stderr ?? '' };
}

const SKILL_A = '---\nname: skill-a\ndescription: Test skill A.\n---\n\nBody of skill A.\n';

function writeMinimalValidFixture(root) {
  writeFile(root, 'CLAUDE.md', '# Test Project\n\nHello.\n');
  writeFile(root, '.claude/skills/dev/skill-a/SKILL.md', SKILL_A);
}

test('1. clean fixture: --write の後は --check が PASS し、生成内容も正しい', () => {
  const root = makeFixture();
  writeMinimalValidFixture(root);

  const w = run(root, ['--write']);
  assert.equal(w.status, 0, w.stdout + w.stderr);

  const c = run(root, ['--check']);
  assert.equal(c.status, 0, c.stdout + c.stderr);

  const agentsMd = readFileSync(join(root, 'AGENTS.md'), 'utf8');
  assert.ok(agentsMd.startsWith('<!-- AUTO-GENERATED by scripts/sync-codex-compat.mjs from CLAUDE.md. DO NOT EDIT. -->\n\n'));
  assert.ok(agentsMd.endsWith('# Test Project\n\nHello.\n'));

  const shim = readFileSync(join(root, '.agents/skills/dev/skill-a/SKILL.md'), 'utf8');
  assert.ok(shim.startsWith('---\nname: skill-a\ndescription: Test skill A.\n---\n\n'));
  assert.ok(shim.includes('Canonical skill instructions: `.claude/skills/dev/skill-a/SKILL.md`'));
  assert.ok(shim.includes('`.claude/skills/dev/skill-a/` directory'));
  assert.ok(!shim.includes('Body of skill A.'), 'shim は本文を複製しない');
});

test('2. CLAUDE.md 変更後、再生成しないと --check が FAIL する', () => {
  const root = makeFixture();
  writeMinimalValidFixture(root);
  assert.equal(run(root, ['--write']).status, 0);

  writeFile(root, 'CLAUDE.md', '# Changed\n');
  const c = run(root, ['--check']);
  assert.equal(c.status, 1);
  assert.match(c.stdout + c.stderr, /AGENTS\.md/);
});

test('3. canonical SKILL.md の frontmatter 変更後、再生成しないと --check が FAIL する', () => {
  const root = makeFixture();
  writeMinimalValidFixture(root);
  assert.equal(run(root, ['--write']).status, 0);

  writeFile(root, '.claude/skills/dev/skill-a/SKILL.md', SKILL_A.replace('Test skill A.', 'Changed description.'));
  const c = run(root, ['--check']);
  assert.equal(c.status, 1);
  assert.match(c.stdout + c.stderr, /mismatch/);
});

test('4. canonical に無い extra ファイルがあると --check が FAIL する', () => {
  const root = makeFixture();
  writeMinimalValidFixture(root);
  assert.equal(run(root, ['--write']).status, 0);

  writeFile(root, '.agents/skills/orphan/SKILL.md', '---\nname: orphan\ndescription: x\n---\n\nOrphan.\n');
  const c = run(root, ['--check']);
  assert.equal(c.status, 1);
  assert.match(c.stdout + c.stderr, /extra/);
});

test('5. canonical SKILL.md が 0 件だと --check / --write が FAIL する（取得失敗ではなく 0 件と分かる形で）', () => {
  const root = makeFixture();
  writeFile(root, 'CLAUDE.md', '# Empty\n');

  const c = run(root, ['--check']);
  assert.equal(c.status, 1);
  assert.match(c.stdout + c.stderr, /0 ?件/);

  const w = run(root, ['--write']);
  assert.equal(w.status, 1);
});

test('6a. frontmatter に description が無いと frontmatter不成立 で FAIL する', () => {
  const root = makeFixture();
  writeFile(root, 'CLAUDE.md', '# T\n');
  writeFile(root, '.claude/skills/dev/bad/SKILL.md', '---\nname: bad\n---\n\nNo description key.\n');

  const c = run(root, ['--check']);
  assert.equal(c.status, 1);
  assert.match(c.stdout + c.stderr, /frontmatter不成立/);
});

test('6b. 同じ name の skill が複数あると skill名重複 で FAIL する', () => {
  const root = makeFixture();
  writeFile(root, 'CLAUDE.md', '# T\n');
  writeFile(root, '.claude/skills/dev/a/SKILL.md', '---\nname: dup\ndescription: A\n---\n\nA.\n');
  writeFile(root, '.claude/skills/dev/b/SKILL.md', '---\nname: dup\ndescription: B\n---\n\nB.\n');

  const c = run(root, ['--check']);
  assert.equal(c.status, 1);
  assert.match(c.stdout + c.stderr, /skill名重複/);
});

test('7. runtime source が .agents/skills を直接参照すると FAIL する（allowlist 外）', () => {
  const root = makeFixture();
  writeMinimalValidFixture(root);
  assert.equal(run(root, ['--write']).status, 0);

  writeFile(root, 'scripts/consumer.mjs', "console.log('.agents/skills/dev/skill-a/foo.mjs');\n");
  const c = run(root, ['--check']);
  assert.equal(c.status, 1);
  assert.match(c.stdout + c.stderr, /runtime consumer/);
});

test('8. --write は不要 payload を削除し、2 回目は written=0 deleted=0 になる', () => {
  const root = makeFixture();
  writeMinimalValidFixture(root);
  writeFile(root, '.agents/skills/stale/SKILL.md', '---\nname: stale\ndescription: x\n---\n\nStale.\n');
  writeFile(root, '.agents/skills/dev/skill-a/scripts/extra.mjs', 'export default 1;\n');

  const w1 = run(root, ['--write']);
  assert.equal(w1.status, 0, w1.stdout + w1.stderr);
  assert.match(w1.stdout, /written=\d+ deleted=\d+ unchanged=\d+/);
  assert.ok(!existsSync(join(root, '.agents/skills/stale')));
  assert.ok(!existsSync(join(root, '.agents/skills/dev/skill-a/scripts')));

  const w2 = run(root, ['--write']);
  assert.equal(w2.status, 0, w2.stdout + w2.stderr);
  assert.match(w2.stdout, /written=0 deleted=0/);
});

test('9. --staged: working tree だけ生成済みで index 未 stage だと FAIL、stage すれば PASS する', () => {
  const root = makeFixture({ git: true });
  writeMinimalValidFixture(root);
  execFileSync('git', ['add', 'CLAUDE.md', '.claude', 'scripts'], { cwd: root });
  execFileSync(
    'git',
    ['-c', 'user.email=t@t.local', '-c', 'user.name=t', '-c', 'commit.gpgsign=false', 'commit', '-q', '-m', 'init'],
    { cwd: root },
  );

  assert.equal(run(root, ['--write']).status, 0);
  const staged1 = run(root, ['--staged']);
  assert.equal(staged1.status, 1, staged1.stdout + staged1.stderr);

  execFileSync('git', ['add', 'AGENTS.md', '.agents'], { cwd: root });
  const staged2 = run(root, ['--staged']);
  assert.equal(staged2.status, 0, staged2.stdout + staged2.stderr);
});

test('10. canonical 側の非 SKILL.md ペイロード（バイナリ含む）は .agents 側へ複製されない', () => {
  const root = makeFixture();
  writeMinimalValidFixture(root);
  const binAbs = join(root, '.claude/skills/dev/skill-a/assets/logo.png');
  mkdirSync(dirname(binAbs), { recursive: true });
  writeFileSync(binAbs, Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x00, 0x01, 0x02, 0xff]));

  assert.equal(run(root, ['--write']).status, 0);
  assert.ok(!existsSync(join(root, '.agents/skills/dev/skill-a/assets')));
});
