/**
 * 総合技術監理キーワード集2026の章・節構造
 * カテゴリページでキーワードをセクション別にグルーピングするために使用
 */

export type PeSection = {
  id: string;    // "2.1"
  title: string; // "事業企画"
};

export type PeChapter = {
  id: string;    // "2"
  title: string; // "経済性管理"
  sections: PeSection[];
};

export const PE_CHAPTERS: PeChapter[] = [
  {
    id: '2', title: '経済性管理', sections: [
      { id: '2.1', title: '事業企画' },
      { id: '2.2', title: '品質の管理' },
      { id: '2.3', title: '工程管理' },
      { id: '2.4', title: '原価管理・管理会計' },
      { id: '2.5', title: '財務会計' },
      { id: '2.6', title: '設備管理' },
      { id: '2.7', title: '計画・管理の数理的手法' },
    ],
  },
  {
    id: '3', title: '人的資源管理', sections: [
      { id: '3.1', title: '人の行動と組織' },
      { id: '3.2', title: '労働関係法と労務管理' },
      { id: '3.3', title: '人材活用計画' },
      { id: '3.4', title: '人材開発' },
    ],
  },
  {
    id: '4', title: '情報管理', sections: [
      { id: '4.1', title: '情報分析と情報活用' },
      { id: '4.2', title: 'コミュニケーション' },
      { id: '4.3', title: '知的財産権と情報の保護と活用' },
      { id: '4.4', title: '情報通信技術動向' },
      { id: '4.5', title: '情報セキュリティ' },
    ],
  },
  {
    id: '5', title: '安全管理', sections: [
      { id: '5.1', title: '安全の概念' },
      { id: '5.2', title: '安全に関するリスクマネジメント' },
      { id: '5.3', title: '労働安全衛生管理' },
      { id: '5.4', title: '事故・災害の未然防止活動・技術' },
      { id: '5.5', title: '危機管理' },
      { id: '5.6', title: 'システム安全工学手法' },
    ],
  },
  {
    id: '6', title: '社会環境管理', sections: [
      { id: '6.1', title: '地球的規模の環境問題' },
      { id: '6.2', title: '地域環境問題' },
      { id: '6.3', title: '環境保全の基本原則' },
      { id: '6.4', title: '組織の社会的責任と環境管理活動' },
    ],
  },
];

/**
 * キーワードslug末尾 → セクション番号の対応表
 * slug例: "pe-comprehensive-management-followership" → キー: "followership" → 値: "3.1"
 */
export const KEYWORD_SECTION_MAP: Record<string, string> = {
  // 2.1 事業企画
  'market-research': '2.1',
  'demand-forecasting': '2.1',
  'investment-recovery-plan': '2.1',
  'discount-rate': '2.1',
  'npv-net-present-value': '2.1',
  'dcf-method': '2.1',
  'payback-period-method': '2.1',
  'internal-rate-of-return': '2.1',
  'cost-effectiveness-analysis': '2.1',
  'outcome-indicators': '2.1',
  'output-indicators': '2.1',
  'input-indicators': '2.1',
  'risk-assessment': '2.1',
  'esg-environmental-assessment': '2.1',
  'lifecycle-management': '2.1',
  'supply-chain-management': '2.1',
  'business-continuity-plan': '2.1',
  'reliability-maintainability-design': '2.1',
  'concurrent-engineering': '2.1',
  'design-review': '2.1',
  'design-in': '2.1',
  'front-loading': '2.1',
  'construction-plan': '2.1',
  'temporary-works-plan': '2.1',
  'process-planning-construction': '2.1',
  'budget-planning': '2.1',
  'safety-health-plan': '2.1',
  'method-planning': '2.1',
  'four-m-of-production': '2.1',
  'pdca-cycle': '2.1',
  'key-performance-indicators': '2.1',
  'pfi': '2.1',
  'pmbok': '2.1',

  // 2.2 品質の管理
  'required-quality': '2.2',
  'design-quality': '2.2',
  'manufacturing-quality': '2.2',
  'quality-characteristics': '2.2',
  'quality-policy': '2.2',
  'quality-objectives': '2.2',
  'quality-planning': '2.2',
  'quality-control': '2.2',
  'quality-assurance': '2.2',
  'quality-improvement': '2.2',
  'product-liability': '2.2',
  'control-limits': '2.2',
  'process-capability-index': '2.2',
  'nonconformity-rate': '2.2',
  'inspection-methods': '2.2',
  'haccp': '2.2',
  'product-safety': '2.2',
  'before-service': '2.2',
  'after-service': '2.2',
  'service-quality': '2.2',

  // 2.3 工程管理
  'pqcdsme': '2.3',
  'jit-production': '2.3',
  'push-production': '2.3',
  'pull-production': '2.3',
  'theory-of-constraints': '2.3',
  'process-scheduling': '2.3',
  'work-planning': '2.3',
  'lead-time': '2.3',
  'utilization-rate': '2.3',
  'load-capacity': '2.3',
  'load-leveling': '2.3',
  'master-schedule-planning': '2.3',
  'gantt-chart': '2.3',
  'bottom-up-estimation': '2.3',
  'analogous-estimation': '2.3',
  'parametric-estimation': '2.3',
  'three-point-estimation': '2.3',
  'pert-cpm': '2.3',
  'progress-management': '2.3',
  'capacity-management': '2.3',
  'inventory-control': '2.3',
  'visual-management': '2.3',
  'five-s': '2.3',
  'ecrs-principle': '2.3',

  // 2.4 原価管理・管理会計
  'direct-manufacturing-cost': '2.4',
  'indirect-manufacturing-cost': '2.4',
  'depreciation-residual-value': '2.4',
  'target-cost': '2.4',
  'process-costing': '2.4',
  'job-order-costing': '2.4',
  'standard-costing': '2.4',
  'direct-costing': '2.4',
  'quality-costing': '2.4',
  'activity-abc': '2.4',
  'cost-driver': '2.4',
  'cost-variance-analysis': '2.4',
  'cost-maintenance': '2.4',
  'lifecycle-costing-method': '2.4',
  'break-even-point': '2.4',
  'wacc-roic': '2.4',

  // 2.5 財務会計
  'balance-sheet': '2.5',
  'income-statement': '2.5',
  'cash-flow-statement': '2.5',
  'ifrs': '2.5',
  'depreciation': '2.5',

  // 2.6 設備管理
  'equipment-characteristics': '2.6',
  'equipment-reliability': '2.6',
  'equipment-maintainability': '2.6',
  'equipment-economics': '2.6',
  'overall-equipment-effectiveness': '2.6',
  'initial-investment': '2.6',
  'planned-usage-period': '2.6',
  'replacement-cost': '2.6',
  'maintenance-cost': '2.6',
  'bathtub-curve': '2.6',
  'autonomous-maintenance': '2.6',
  'periodic-maintenance': '2.6',
  'predictive-maintenance': '2.6',
  'corrective-maintenance': '2.6',
  'preventive-maintenance': '2.6',
  'improvement-maintenance': '2.6',
  'maintenance-prevention': '2.6',

  // 2.7 計画・管理の数理的手法
  'cause-and-effect-diagram': '2.7',
  'idea-generation-methods': '2.7',
  'delphi-method': '2.7',
  'pdpc-method': '2.7',
  'monte-carlo-simulation': '2.7',
  'linear-programming': '2.7',
  'integer-programming': '2.7',
  'multi-objective-optimization': '2.7',
  'game-theory': '2.7',
  'analytic-hierarchy-process': '2.7',
  'economic-comparison-principle': '2.7',
  'present-annual-future-value': '2.7',
  'opportunity-cost': '2.7',
  'value-engineering': '2.7',

  // 3.1 人の行動と組織
  'diagnostic-od': '3.1',
  'dialogic-od': '3.1',
  'content-process': '3.1',
  'incentive': '3.1',
  'extrinsic-motivation': '3.1',
  'intrinsic-motivation': '3.1',
  'organizational-commitment': '3.1',
  'psychological-safety': '3.1',
  'wellbeing-org': '3.1',
  'functional-organization': '3.1',
  'divisional-organization': '3.1',
  'matrix-organization': '3.1',
  'flat-organization': '3.1',
  'network-organization': '3.1',
  'pyramid-organization': '3.1',
  'teal-organization': '3.1',
  'achievement-organization': '3.1',
  'mcgregor-xy-theory': '3.1',
  'maslow-hierarchy-of-needs': '3.1',
  'herzberg-two-factor-theory': '3.1',
  'asch-conformity-experiment': '3.1',
  'pm-theory': '3.1',
  'sl-theory': '3.1',
  'servant-leadership': '3.1',
  'followership': '3.1',
  'hawthorne-experiment': '3.1',
  'scientific-management': '3.1',

  // 3.2 労働関係法と労務管理
  'labor-standards-act': '3.2',
  'labor-union-act': '3.2',
  'labor-relations-adjustment-act': '3.2',
  'individual-labor-dispute-act': '3.2',
  'labor-tribunal-act': '3.2',
  'labor-contract-act': '3.2',
  'minimum-wage-act': '3.2',
  'occupational-safety-act': '3.2',
  'employment-security-act': '3.2',
  'vocational-training-act': '3.2',
  'part-time-fixed-term-act': '3.2',
  'elderly-employment-act': '3.2',
  'disability-employment-act': '3.2',
  'disability-discrimination-act': '3.2',
  'worker-dispatch-act': '3.2',
  'equal-employment-act': '3.2',
  'gender-equality-act': '3.2',
  'women-empowerment-act': '3.2',
  'child-rearing-support-act': '3.2',
  'childcare-nursing-leave-act': '3.2',
  'immigration-control-act': '3.2',
  'labor-policy-act': '3.2',
  'youth-employment-act': '3.2',
  'lgbt-understanding-act': '3.2',
  'child-support-act': '3.2',
  'total-wage-management': '3.2',
  'individual-wage-management': '3.2',
  'job-based-pay': '3.2',
  'skill-based-pay': '3.2',
  'annual-salary-system': '3.2',
  'seniority-wage': '3.2',
  'performance-based-pay': '3.2',
  'performance-linked-bonus': '3.2',
  'equal-pay-for-equal-work': '3.2',
  'labor-productivity': '3.2',
  'labor-share-ratio': '3.2',
  'work-life-balance': '3.2',
  'flextime-system': '3.2',
  'variable-work-hours': '3.2',
  'discretionary-work-system': '3.2',
  'return-to-work-support': '3.2',
  'side-jobs': '3.2',
  'health-management': '3.2',
  'stress-check-system': '3.2',
  'mental-health-care': '3.2',
  'highly-professional-system': '3.2',
  'reemployment-system-labor': '3.2',
  'indefinite-conversion-rule': '3.2',
  'employee-benefits': '3.2',
  'employment-insurance': '3.2',
  'workers-compensation-insurance': '3.2',
  'pension-system': '3.2',
  'power-harassment': '3.2',
  'sexual-harassment': '3.2',
  'labor-mobility': '3.2',
  'employment-statistics': '3.2',
  'human-capital-disclosure': '3.2',

  // 3.3 人材活用計画
  'formal-informal-organization': '3.3',
  'personnel-management': '3.3',
  'skill-qualification-system': '3.3',
  'job-grade-system': '3.3',
  'role-grade-system': '3.3',
  'multi-track-hr-system': '3.3',
  'location-limited-employee': '3.3',
  'specialist-system': '3.3',
  'internal-job-posting': '3.3',
  'reemployment-system': '3.3',
  'continued-employment-system': '3.3',
  'self-declaration-system': '3.3',
  'job-type-employment': '3.3',
  'membership-type-employment': '3.3',
  'career-track-system': '3.3',
  'job-analysis': '3.3',
  'job-design': '3.3',
  'recruitment-management': '3.3',
  'second-career': '3.3',
  'mandatory-management-retirement': '3.3',
  'disability-employment': '3.3',
  'gender-gap': '3.3',
  'lgbtq': '3.3',
  'positive-action': '3.3',
  'unconscious-bias': '3.3',
  'talent-management': '3.3',
  'internship': '3.3',

  // 3.4 人材開発
  'attitude-appraisal': '3.4',
  'performance-evaluation': '3.4',
  'competency-evaluation': '3.4',
  '360-degree-evaluation': '3.4',
  'mbo': '3.4',
  'merit-demerit-system': '3.4',
  'appraisal-three-principles': '3.4',
  'relative-absolute-evaluation': '3.4',
  'evaluation-bias': '3.4',
  'halo-effect-errors': '3.4',
  'hierarchical-training': '3.4',
  'specialized-training': '3.4',
  'task-based-training': '3.4',
  'self-development': '3.4',
  'e-learning': '3.4',
  'ojt-off-jt': '3.4',
  'problem-setting-ability': '3.4',
  'job-execution-ability': '3.4',
  'interpersonal-skills': '3.4',
  'problem-solving-ability': '3.4',
  'competency-hr': '3.4',
  'global-hr-development': '3.4',
  'reskilling': '3.4',
  'mentor': '3.4',
  'training-techniques': '3.4',
  'human-resource-assessment': '3.4',
  'skill-standards': '3.4',
  'cpd': '3.4',
  'job-rotation': '3.4',
  'qc-circle': '3.4',
  'foreign-trainee-program': '3.4',
  'career-path': '3.4',
  'career-ownership': '3.4',

  // 4.1 情報分析と情報活用
  'survey-analysis': '4.1',
  'information-retrieval': '4.1',
  'recommendation-systems': '4.1',
  'descriptive-statistics': '4.1',
  'linear-regression': '4.1',
  'logistic-regression': '4.1',
  'correlation-analysis': '4.1',
  'estimation-testing': '4.1',
  'data-collection': '4.1',
  'data-cleansing': '4.1',
  'data-mining': '4.1',
  'cluster-analysis': '4.1',
  'data-visualization': '4.1',
  'machine-learning': '4.1',
  'generative-ai': '4.1',
  'swot-analysis': '4.1',
  'value-chain-analysis': '4.1',
  'three-c-analysis': '4.1',
  'four-p-analysis': '4.1',
  'ppm-analysis': '4.1',
  'explicit-knowledge': '4.1',
  'tacit-knowledge': '4.1',
  'collective-intelligence': '4.1',
  'data-warehouse': '4.1',
  'knowledge-sharing': '4.1',
  'design-thinking': '4.1',
  'public-private-data-act': '4.1',

  // 4.2 コミュニケーション
  'verbal-nonverbal-communication': '4.2',
  'mass-communication': '4.2',
  'personal-communication': '4.2',
  'information-disclosure': '4.2',
  'disclosure-request': '4.2',
  'public-acceptance-comm': '4.2',
  'stakeholder': '4.2',
  'information-disclosure-act': '4.2',
  'right-to-know': '4.2',
  'disclosure-standards': '4.2',
  'public-relations': '4.2',
  'citizen-participation': '4.2',
  'groupware': '4.2',
  'online-meetings': '4.2',
  'communication-planning': '4.2',
  'meeting-design': '4.2',
  'communication-control': '4.2',
  'emergency-info-systems': '4.2',
  'emergency-info-processing': '4.2',

  // 4.3 知的財産権と情報の保護と活用
  'industrial-property-rights': '4.3',
  'patent-rights': '4.3',
  'utility-model-rights': '4.3',
  'design-rights': '4.3',
  'trademark-rights': '4.3',
  'copyright': '4.3',
  'prior-use-rights': '4.3',
  'international-filing-system': '4.3',
  'state-secrets-act': '4.3',
  'unfair-competition-prevention-act': '4.3',
  'portrait-publicity-privacy': '4.3',
  'digital-rights': '4.3',
  'personal-information': '4.3',
  'anonymized-information': '4.3',
  'personal-info-protection': '4.3',
  'opt-in-opt-out': '4.3',
  'personal-info-utilization': '4.3',
  'data-breach-response': '4.3',
  'my-number-act': '4.3',
  'private-monopoly': '4.3',
  'unreasonable-trade-restraint': '4.3',
  'unfair-trade-practices': '4.3',
  'subcontracting-act': '4.3',
  'antitrust-compliance': '4.3',
  'bid-rigging': '4.3',
  'ip-creation': '4.3',
  'ip-protection': '4.3',
  'ip-utilization': '4.3',
  'standardization-strategy': '4.3',
  'de-jure-standard': '4.3',
  'forum-standard': '4.3',
  'de-facto-standard': '4.3',
  'technology-licensing': '4.3',

  // 4.4 情報通信技術動向
  'centralization-decentralization': '4.4',
  'web-services': '4.4',
  'cloud-on-premises': '4.4',
  'edge-computing': '4.4',
  'system-reliability': '4.4',
  'system-availability': '4.4',
  'system-serviceability': '4.4',
  'system-integrity': '4.4',
  'system-security': '4.4',
  'internet': '4.4',
  'fixed-communication': '4.4',
  'mobile-communication': '4.4',
  'erp': '4.4',
  'accounting-systems': '4.4',
  'hr-systems': '4.4',
  'sales-management-system': '4.4',
  'crm-system': '4.4',
  'sfa-system': '4.4',
  'production-management-system': '4.4',
  'scm-system': '4.4',
  'enterprise-portal-intranet': '4.4',
  'business-intelligence': '4.4',
  'rpa': '4.4',
  'digital-twin-cps': '4.4',
  'iot': '4.4',
  'vr-ar-metaverse': '4.4',
  'blockchain-crypto': '4.4',
  'api': '4.4',
  'waterfall': '4.4',
  'agile': '4.4',

  // 4.5 情報セキュリティ
  'confidentiality': '4.5',
  'integrity-security': '4.5',
  'availability-security': '4.5',
  'authenticity': '4.5',
  'accountability-traceability': '4.5',
  'reliability-security': '4.5',
  'non-repudiation': '4.5',
  'data-governance': '4.5',
  'security-education': '4.5',
  'data-leak-tampering-loss': '4.5',
  'system-outage-degradation': '4.5',
  'unauthorized-access': '4.5',
  'operation-errors': '4.5',
  'malware': '4.5',
  'dos-ddos': '4.5',
  'targeted-attack': '4.5',
  'phishing-pharming': '4.5',
  'social-engineering': '4.5',
  'vulnerability': '4.5',
  'security-software': '4.5',
  'password-security': '4.5',
  'access-control': '4.5',
  'access-log-analysis': '4.5',
  'threat-awareness-training': '4.5',
  'firewall-ids': '4.5',
  'encryption-digital-signature': '4.5',
  'vpn': '4.5',
  'dmz': '4.5',
  'multi-factor-authentication': '4.5',
  'zero-trust': '4.5',
  'isms-iso27001': '4.5',
  'common-criteria': '4.5',
  'jisec': '4.5',
  'ismap': '4.5',
  'privacy-mark': '4.5',
  'cyber-security': '4.5',

  // 5.1 安全の概念
  'safety-management-system': '5.1',
  'safety-control': '5.1',
  'safety-objectives': '5.1',
  'safety-investment': '5.1',
  'disaster-prevention': '5.1',
  'resilience': '5.1',
  'all-hazard-approach': '5.1',
  'public-safety': '5.1',
  'consumer-safety': '5.1',
  'aging-infrastructure': '5.1',
  'smart-safety': '5.1',
  'cybersecurity-safety': '5.1',
  'process-safety-mgmt': '5.1',
  'system-safety': '5.1',
  'product-safety-process': '5.1',
  'fire-service-act': '5.1',
  'high-pressure-gas-act': '5.1',
  'consumer-product-safety-act': '5.1',
  'product-liability-act': '5.1',
  'machinery-safety-guidelines': '5.1',
  'safety-2-0': '5.1',
  'elsi': '5.1',
  'safety-culture': '5.1',
  'safety-and-security': '5.1',

  // 5.2 安全に関するリスクマネジメント
  'risk': '5.2',
  'hazard': '5.2',
  'risk-map-matrix': '5.2',
  'likelihood': '5.2',
  'impact': '5.2',
  'risk-management-plan': '5.2',
  'risk-criteria': '5.2',
  'risk-management-system': '5.2',
  'risk-management-policy': '5.2',
  'risk-identification': '5.2',
  'risk-analysis': '5.2',
  'risk-evaluation': '5.2',
  'risk-treatment': '5.2',
  'risk-monitoring': '5.2',
  'public-acceptance': '5.2',
  'risk-perception': '5.2',
  'alarp-principle': '5.2',
  'residual-risk': '5.2',
  'normalcy-bias': '5.2',
  'optimism-bias': '5.2',
  'catastrophe-bias': '5.2',
  'conformity-bias': '5.2',
  'veteran-bias': '5.2',
  'virgin-bias': '5.2',

  // 5.3 労働安全衛生管理
  'accident-statistics': '5.3',
  'accident-cost': '5.3',
  'occupational-disease': '5.3',
  'mental-health': '5.3',
  'labor-standards-act-osh': '5.3',
  'occupational-safety-act-osh': '5.3',
  'osh-management-system': '5.3',
  'oshms': '5.3',
  'safety-health-policy': '5.3',
  'safety-health-education': '5.3',
  'safety-health-org-structure': '5.3',

  // 5.4 事故・災害の未然防止活動・技術
  'safety-education': '5.4',
  'accident-response-drill': '5.4',
  'disaster-drill': '5.4',
  'blind-drill': '5.4',
  'unsafe-conditions-behavior': '5.4',
  'human-factors': '5.4',
  'heinrich-law': '5.4',
  'inherent-safety': '5.4',
  'functional-safety': '5.4',
  'ergonomic-principles': '5.4',
  'safety-instrumented-system': '5.4',
  'emergency-stop-device': '5.4',
  'fault-avoidance': '5.4',
  'fault-tolerance': '5.4',
  'fail-soft': '5.4',
  'fool-proof': '5.4',
  'fail-safe': '5.4',
  'interlock': '5.4',
  'safety-confirmation-system': '5.4',
  'isolation-stop-safety': '5.4',
  'redundancy-safety': '5.4',
  'safety-case': '5.4',
  'lopa': '5.4',
  'technical-nontechnical-skills': '5.4',
  'four-m-analysis': '5.4',
  'four-e-countermeasures': '5.4',
  'small-group-activities': '5.4',
  'occupational-accident-prevention-plan': '5.4',
  'prevention-activities': '5.4',
  'periodic-inspection': '5.4',
  'kyt': '5.4',
  'tbm-toolbox-meeting': '5.4',
  'sop': '5.4',
  'safety-patrol': '5.4',

  // 5.5 危機管理
  'emergency': '5.5',
  'contingency': '5.5',
  'extreme-events': '5.5',
  'disaster-weather-info': '5.5',
  'liquefaction': '5.5',
  'alert-levels': '5.5',
  'timeline-disaster': '5.5',
  'natech': '5.5',
  'hazardous-facility-disaster-prevention': '5.5',
  'probabilistic-risk-assessment': '5.5',
  'defense-in-depth': '5.5',
  'terrorism': '5.5',
  'infectious-disease-pandemic': '5.5',
  'crisis-communication': '5.5',
  'crisis-priority': '5.5',
  'crisis-management-manual': '5.5',
  'civil-protection-act': '5.5',
  'disaster-countermeasures-act': '5.5',
  'national-resilience-act': '5.5',
  'bcp-crisis-management': '5.5',
  'ics': '5.5',

  // 5.6 システム安全工学手法
  'fmea': '5.6',
  'hazop': '5.6',
  'hazid': '5.6',
  'decision-tree-analysis': '5.6',
  'fta': '5.6',
  'eta': '5.6',
  'bowtie-analysis': '5.6',
  'pha': '5.6',
  'human-error-probability': '5.6',
  'tripod-theory': '5.6',
  'therp': '5.6',
  'performance-shaping-factors': '5.6',
  'vta-method': '5.6',
  'reliability-block-diagram': '5.6',
  'series-system': '5.6',
  'parallel-system': '5.6',
  'root-cause-analysis': '5.6',

  // 6.1 地球的規模の環境問題
  'un-human-environment-conf': '6.1',
  'club-of-rome': '6.1',
  'wced': '6.1',
  'unced-earth-summit': '6.1',
  'rio-declaration': '6.1',
  'agenda-21': '6.1',
  'ecological-footprint': '6.1',
  'human-development-index': '6.1',
  'sdgs': '6.1',
  'decoupling': '6.1',
  'ozone-layer-protection': '6.1',
  'acid-rain': '6.1',
  'planetary-boundaries': '6.1',
  'doughnut-economics': '6.1',
  'climate-change-international': '6.1',
  'climate-change-decarbonization': '6.1',
  'energy': '6.1',
  'kunming-montreal-framework': '6.1',
  'nagoya-protocol': '6.1',
  'biosafety': '6.1',
  'ipbes': '6.1',
  'millennium-ecosystem-assessment': '6.1',
  'ecosystem-services': '6.1',
  'nature-positive': '6.1',
  'satoyama-initiative': '6.1',
  'red-list': '6.1',
  'ramsar-convention': '6.1',
  'cites': '6.1',
  'convention-on-biodiversity': '6.1',
  'biodiversity-basic-act': '6.1',
  'nature-conservation-act': '6.1',
  'natural-parks-act': '6.1',
  'species-preservation-act': '6.1',
  'nature-restoration-act': '6.1',
  'wildlife-protection-act': '6.1',
  'invasive-alien-species': '6.1',
  'forests-villages-rivers-seas': '6.1',

  // 6.2 地域環境問題
  'circular-economy': '6.2',
  'regional-circular-symbiosis': '6.2',
  'circular-society-basic-act': '6.2',
  'waste-management-act': '6.2',
  'basel-convention': '6.2',
  'e-waste': '6.2',
  'ocean-plastic': '6.2',
  'sustainable-fashion': '6.2',
  'sound-water-cycle': '6.2',
  'four-major-pollution-diseases': '6.2',
  'seven-types-of-pollution': '6.2',
  'air-pollution-control-act': '6.2',
  'water-pollution-control-act': '6.2',
  'soil-contamination-act': '6.2',
  'asbestos-issue': '6.2',
  'gfc-chemicals-framework': '6.2',
  'pops-convention': '6.2',
  'minamata-convention': '6.2',
  'reach-regulation': '6.2',
  'rohs-weee': '6.2',
  'dioxin-countermeasures-act': '6.2',
  'chemical-substances-review-act': '6.2',
  'prtr-act': '6.2',
  'heat-island-effect': '6.2',
  'urban-flood': '6.2',
  'hazard-map': '6.2',
  'eco-drr': '6.2',
  'green-infrastructure': '6.2',
  'nuclear-disaster-act': '6.2',
  'radioactive-decontamination-act': '6.2',
  'radioactive-waste': '6.2',
  'interim-storage-facility': '6.2',
  'alps-treated-water': '6.2',
  'clearance-level': '6.2',

  // 6.3 環境保全の基本原則
  'environmental-basic-plan': '6.3',
  'environmental-standards': '6.3',
  'polluter-pays-principle': '6.3',
  'extended-producer-responsibility': '6.3',
  'prevention-principle': '6.3',
  'precautionary-principle': '6.3',
  'source-control-principle': '6.3',
  'partnership': '6.3',
  'subsidiarity-principle': '6.3',
  'end-of-pipe': '6.3',
  'performance-regulation': '6.3',
  'behavioral-regulation': '6.3',
  'carbon-pricing': '6.3',
  'surcharge': '6.3',
  'deposit-system': '6.3',
  'eco-label': '6.3',
  'environmental-impact-assessment': '6.3',
  'consensus-instruments': '6.3',
  'backcasting': '6.3',
  'lifecycle-assessment': '6.3',
  'esd': '6.3',

  // 6.4 組織の社会的責任と環境管理活動
  'pollution-control-manager': '6.4',
  'csr': '6.4',
  'csv': '6.4',
  'sri': '6.4',
  'esg-investment': '6.4',
  'green-bond': '6.4',
  'tcfd': '6.4',
  'tnfd': '6.4',
  'cdp-sbt-re100': '6.4',
  'global-compact': '6.4',
  'iso-14000': '6.4',
  'eco-action-21': '6.4',
  'iso-26000': '6.4',
  'bioeconomy': '6.4',
  'design-for-environment': '6.4',
  'environmental-accounting': '6.4',
  'environmental-communication': '6.4',
};

/**
 * slugからキーワード部分を抽出
 * "pe-comprehensive-management-followership" → "followership"
 */
export function extractKeywordSlug(fullSlug: string): string {
  return fullSlug.replace(/^pe-comprehensive-management-/, '');
}

/**
 * キーワードが属するセクション番号を返す（未登録はnull）
 */
export function getKeywordSection(fullSlug: string): string | null {
  const key = extractKeywordSlug(fullSlug);
  return KEYWORD_SECTION_MAP[key] ?? null;
}
